include("$(BOARD_DIR)/../manifest.py")
require("lora-sync")
require("lora-sx126x")
require("lora-sx127x")
freeze("../drivers")
module("marg.py", base_path="$(MPY_DIR)/../model-rocketry/nene/lil-buddy/")
module("uftpd.py", base_path="$(MPY_DIR)/../FTP-Server-for-ESP8266-ESP32-and-PYBD")
c_module("$(MPY_DIR)/../micropython-ulab/code")
c_module("$(MPY_DIR)/../model-rocketry/nene/lil-buddy/c-modules/fusion_wrapper")
c_module("$(MPY_DIR)/../model-rocketry/nene/lil-buddy/c-modules/hidden_buffer")